name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 打标签时触发（如 git tag -a v1.0 -m "Release" && git push --tags）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动拥有权限
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/TiebaSignIn-1.0-SNAPSHOT-jar-with-dependencies.jar
          asset_name: TiebaSignIn.jar  # 重命名为简洁名称
          asset_content_type: application/java-archive

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 使用推送的标签（如 v1.0）
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
