# .github/workflows/build-and-release.yml
name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build fat JAR
        run: |
          mvn clean compile assembly:single
          ls -la target/*.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: target/*-jar-with-dependencies.jar
          body: "包含所有依赖的可执行JAR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
