name: Run Tieba SignIn

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '10 0 * * *'  # 每天 UTC 0:10（北京时间 8:10）自动运行

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven dependencies and build output
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.m2/repository
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build only if cache missed
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn package

      - name: Run the application
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          java -jar "$JAR_FILE" "${BDUSS}" "${SCKEY}"
