jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven and build output
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.m2/repository
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build only if cache missed
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn package

      - name: Run the application
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          # 动态匹配 JAR 文件（推荐）
          JAR_FILE=$(ls target/*.jar | head -n 1)
          java -jar "$JAR_FILE" "${BDUSS}" "${SCKEY}"
