# .github/workflows/run-from-release.yml
name: Run from Release

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        run: |
          mkdir -p ./app
          curl -L -o ./app/TiebaSignIn.jar \
            "https://github.com/ZhianLin/TiebaSignIn-1/releases/latest/download/TiebaSignIn.jar"
          
      - name: Verify JAR
        run: |
          if ! unzip -q -t ./app/TiebaSignIn.jar; then
            echo "::error::JAR文件损坏或下载失败"
            exit 1
          fi

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run Application
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          java -jar ./app/TiebaSignIn.jar "${BDUSS}" "${SCKEY}"
