name: Run Tieba SignIn

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '10 0 * * *'  # 每天 UTC 0:10（北京时间 8:10）自动运行

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR from Release
        run: |
          mkdir -p ./downloaded-jar
          curl -L -o ./downloaded-jar/TiebaSignIn.jar \
            https://github.com/ZhianLin/TiebaSignIn-1/releases/download/master/TiebaSignIn.jar

      - name: Verify JAR exists
        run: |
          ls -la ./downloaded-jar/
          [ -f ./downloaded-jar/TiebaSignIn.jar ] || exit 1

      - name: Set up JDK 8 (for execution only)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run the application
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          java -jar ./downloaded-jar/TiebaSignIn.jar "${BDUSS}" "${SCKEY}"
