name: Run Tieba SignIn

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR
        run: |
          mkdir -p ./downloaded-jar
          curl -L -o ./downloaded-jar/TiebaSignIn.jar \
            https://github.com/ZhianLin/TiebaSignIn-1/releases/download/master/TiebaSignIn.jar

      - name: Verify JAR
        run: |
          if ! unzip -q -t ./downloaded-jar/TiebaSignIn.jar; then
            echo "::error::Downloaded JAR is corrupt"
            exit 1
          fi

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run (with fallback)
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          # 尝试两种运行方式
          if java -jar ./downloaded-jar/TiebaSignIn.jar "${BDUSS}" "${SCKEY}"; then
            exit 0
          else
            echo "::warning::Fallback to explicit class execution"
            java -cp ./downloaded-jar/TiebaSignIn.jar top.srcrs.Run "${BDUSS}" "${SCKEY}"
          fi
